package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.10
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("routes",
                                              "used to make transactions between mobile app and routes dynamodb table",
                                              "https://20v8fpib92.execute-api.us-west-2.amazonaws.com/Development",
                                              new String[] {
                                                  "/getRoutes",
                                                  "/storeRoutes",
                                                  "/useRoute",
                                                  "/getRoutes/123",
                                                  "/storeRoutes/123",
                                                  "/useRoute/123",
                                              },
                                              com.amazonaws.mobile.api.id20v8fpib92.RoutesMobileHubClient.class),
                new CloudLogicAPIConfiguration("biker",
                                              "allows for transactions between mobile app and the dynamodb tables",
                                              "https://m4p6j74mol.execute-api.us-west-2.amazonaws.com/Development",
                                              new String[] {
                                                  "/createUser",
                                                  "/verifyUser",
                                                  "/createUser/123",
                                                  "/verifyUser/123",
                                              },
                                              com.amazonaws.mobile.api.idm4p6j74mol.BikerMobileHubClient.class),
        };

        return apis;
    }
}
